In [1]:
from env import WindyEnv
import numpy as np
from tqdm import tqdm

In [2]:
class SarsaAgent:
    def __init__(self, env, alpha=0.5, epsilon=0.1, gamma=1):
        self.env = env
        self.alpha = alpha
        self.epsilon = epsilon
        self.gamma = gamma
        self.q = np.zeros((len(env.state_space), len(env.action_space)))
        self.pi = np.zeros((len(env.state_space), len(env.action_space)))
        self.pi[:, :] = 1 / len(env.action_space)
        print(self.pi)

        self.train()
    
    def derive_policy_from_q(self):
        self.pi = np.zeros((len(self.env.state_space), len(self.env.action_space)))
        for i in range(len(self.env.state_space)):
            best_a = np.argmax(self.q[i])
            self.pi[i, best_a] = 1 - self.epsilon + self.epsilon / len(self.env.action_space)
            for a in range(len(self.env.action_space)):
                if a != best_a:
                    self.pi[i, a] = self.epsilon / len(self.env.action_space)
    

    def train(self, episodes=1000):
        for _ in tqdm(range(episodes)):
            state = self.env.reset()
            s = self.env.state_space.index(state)
            a = np.random.choice([0,1,2,3], p=self.pi[s])
            
            i = 0
            while True:
                action = self.env.action_space[a]
                state_, r, done = self.env.step(action)
                s_ = self.env.state_space.index(state_)
                a_ = np.random.choice([0,1,2,3], p=self.pi[s_])
                self.q[s, a] += self.alpha * (r + self.gamma * self.q[s_, a_] - self.q[s, a])
                s = s_
                a = a_
                if done:
                    print(i)
                    i=0
                    break
                    
                i += 1
            

    

In [3]:
agent = SarsaAgent(WindyEnv(10,7,[0,0,0,1,1,1,2,2,1,0]),alpha=0.1,epsilon=0.1,gamma=1)

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25

  0%|          | 1/1000 [00:00<12:35,  1.32it/s]

20373


  0%|          | 2/1000 [00:03<36:17,  2.18s/it]

87276


  0%|          | 3/1000 [00:04<26:05,  1.57s/it]

22656


  0%|          | 5/1000 [00:05<13:20,  1.24it/s]

11099
5011


  1%|          | 6/1000 [00:07<17:33,  1.06s/it]

43492
54118
8395


  1%|          | 9/1000 [00:07<08:28,  1.95it/s]

19440


  1%|          | 10/1000 [00:08<09:42,  1.70it/s]

32113


  1%|          | 11/1000 [00:11<20:22,  1.24s/it]

130592


  1%|          | 12/1000 [00:12<17:18,  1.05s/it]

17557
779


  1%|▏         | 14/1000 [00:15<21:37,  1.32s/it]

128809


  2%|▏         | 15/1000 [00:16<21:39,  1.32s/it]

48451


  2%|▏         | 16/1000 [00:17<18:50,  1.15s/it]

23593


  2%|▏         | 17/1000 [00:18<19:36,  1.20s/it]

50059


  2%|▏         | 18/1000 [00:20<20:49,  1.27s/it]

51795
2433


  2%|▏         | 21/1000 [00:21<11:48,  1.38it/s]

27776
4092


  2%|▏         | 22/1000 [00:23<16:53,  1.04s/it]

74215
919


  2%|▎         | 25/1000 [00:23<09:32,  1.70it/s]

22344
3349


  3%|▎         | 26/1000 [00:24<11:05,  1.46it/s]

32994


  3%|▎         | 27/1000 [00:26<16:27,  1.01s/it]

72657


  3%|▎         | 29/1000 [00:27<10:56,  1.48it/s]

19675
5302


  3%|▎         | 31/1000 [00:28<08:19,  1.94it/s]

21402
4378


  3%|▎         | 32/1000 [00:28<06:23,  2.52it/s]

2794


  3%|▎         | 34/1000 [00:30<09:37,  1.67it/s]

59167
6443


  4%|▎         | 35/1000 [00:30<07:34,  2.12it/s]

3387
1786


  4%|▎         | 37/1000 [00:30<05:18,  3.02it/s]

7679


  4%|▍         | 38/1000 [00:32<09:28,  1.69it/s]

45099


  4%|▍         | 39/1000 [00:32<08:39,  1.85it/s]

11921
